# ===================================================================
# 开发工具时时默认的配置
#
# 所有相对路径以本项目根目录为准
# ===================================================================

generator:
  env: dev
  api-prefix: api
  template-path: ./resources/generator

  test-host: http://localhost

  writers:
    postman:
      enabled: true
      path: .
    testcases:
      enabled: true
      path: ./resources/generator/testcases

    laravel:
      enabled: true
      path: .

      bo-suffix: BO
      bo-folder: BOs
      dto-suffix: DTO
      dto-folder: DTOs
      service-suffix: Service
      service-folder: Services
    laravel-doc:
      enabled: true
      path: .
      http-prefix: docs
    laravel-auto-test:
      enabled: true
      path: .
      force-replace: false
      testcases-path: ./resources/generator/testcases


    nodejs-client:
      enabled: true
      output: ./src/output/nodejs-client

spring:
  profiles:
    active: prod
  thymeleaf:
    mode: TEXT
    suffix: .stub
    encoding: UTF-8
    prefix: classpath:/templates/
